from docx import Document
from docx.shared import Inches
import pyttsx3

def speak(text):
    pyttsx3.speak(text)

document = Document()

document.add_picture("profile.jpg",width=Inches(2.0))

name = input('what is your name')
speak("hello" + name + 'how are you today ?')
phone_number = input('your name')
email = input('what is your email')

document.add_paragraph(name +' ' + '\n'+ phone_number +' ' + "\n" + email)

document.add_heading('About me')
about_me = input('tell us about yourself')
document.add_paragraph(about_me)

document.add_heading('work experience')
p = document.add_paragraph

company = input('enter company')
from_date = input('from date')
to_date = input('to date')

p.add_run(company +  ' ').bold = True

p.add_run(from_date +  '-'+ to_date + '\n').italic = True

experience_details = input('describe your experience at ' + company)
p.add_run(experience_details)

while True:
    more_experiences = input("do you have more experiences? yes or no ")
    if more_experiences.lower == 'yes':
        p = document.add_paragraph(more_experiences)

        company = input('enter company')
        from_date = input('from date')
        to_date = input('to date')

        p.add_run(company +  ' ').bold = True

        p.add_run(from_date +  '-'+ to_date + '\n').italic = True

        experience_details = input('describe your experience at ' + company +' ')
        p.add_run(experience_details)
    else:
     break
 #skills
document.add_heading('skills')
skill = input('enter skill')
p = document.add_paragraph(skill)
p.style ='List Bullet'

while True:
    more_skills = input("do you have more skills? yes or no ")
    if more_skills.lower == 'yes':
        skill = input('enter skill')
        p = document.add_paragraph(skill)
        p.style ='List Bullet'
    else:
        break
    #footer
    section = document.sections[0]
    footer = section.footer
    p = footer.paragraphs[0]
    p.text = 'cv  generated by omwesigye'

document.save('cv.dox')